### ISSUE TITLE
Pin assignment of segment display in Quartus

### ISSUE THREAD

**Issue by dnlnm** [widcardw/Clock#1]
I try to run your project in quartus and upload it to the fpga board, but I confuse in pin planner for the segment display.
Which output should I assign to the 7 segment display?

**Comment by widcardw** [comment]
Sorry for my fault that I forgot to upload the pin planner of the fpga board. Now you can download the document with several pictures that explains the pins. The [document](https://github.com/widcardw/Clock/blob/main/DE2-70-pins.doc) is right here.

**Comment by dnlnm** [comment]
![pin](https://user-images.githubusercontent.com/80830846/124149484-35bd2c00-dac3-11eb-8242-35d056189c27.PNG)

Sorry for asking to much because I'm new to this. Based on the picture above, it is for the second segment right? So we have to assign it based on the document you send right? If the segS[0] to [6] for the HEX0, is this mean segS[7] to [13] for HEX1? What is segS[14] and [15] for?

**Comment by widcardw** [comment]
Oh, the segS means the two decimal numbers of second, and segS[7:0] means the HEX0 including the decimal point (that is segS[7]). In the file `Clock.v` we know the correspondences:
```
segS[7:0]=HEX0  // the low bit of decimal second
segS[15:8]=HEX1  // the high bit of decimal second
```
and so on.
Since it was long time I uploaded the project, I even could not remember some of these parts😷

**Comment by dnlnm** [comment]
Oh..thats ok. But im still confuse here. Did you have csv file for assigned pin? Perhaps I can see and compare it because I using Altera DE10-Standard

**Comment by widcardw** [comment]
I'm sorry but our teacher just gave us the doc instead of a csv file, so I can only use OCR to turn the pictures to text... And it's too late in China so I'll do this tomorrow😖

**Comment by dnlnm** [comment]
What i mean is when you do the project, you assign the pin right. I want to see what pin you assign to each output. By that, I can compare it with the DE10 user manual and assign the pin on my board. By the way, Tq for reply me this late, sorry for disturb you.

**Comment by dnlnm** [comment]
You have any update?

**Comment by widcardw** [comment]
The [csv file](https://github.com/widcardw/Clock/blob/main/all_pins.csv) is uploaded now. 

BTW, the assignments may make you confused because many of them are not used, only `segS, segM, segH` are intended for the digital display of the clock. And the **Adder part of the bell** is distinguished from that of the **main clock**, and it hasn't been fully tested yet (because the problem was found when the exam took place, and I almost have no chance to fix it). As you can see the code of `BellCtrl.v` is really awkward because I just wrote a new adder to change the hexadecimal to decimal numbers. 

So feel free to raise problems and I will view the changes. Good luck bro!

**Comment by dnlnm** [comment]
Ok understand. Tq for the file and just to make sure can you confirm what is working and what still not fully tested. Very appreciate it.
